server.port=8080

spring.application.name=api-gateway

app.jwt.secret=mi_clave_secreta_super_segura_12345678901234567890
app.jwt.expiration=3600000

spring.cloud.gateway.server.webflux.routes[0].id=adminred-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/centros/**,/api/especialidades/**

spring.cloud.gateway.server.webflux.routes[1].id=gestion-clinica-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/clinica/**

# Django Microservice
spring.cloud.gateway.server.webflux.routes[2].id=django-identity-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8000
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/**