spring.application.name=ms-gestion-clinica

server.port=${SERVER_PORT:8082}

# MySQL (XAMPP/phpMyAdmin)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/rednorte_clinica?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Santiago}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Resilience4j circuit breaker for peripheral hospitals
resilience4j.circuitbreaker.instances.hospitalPeriferico.slidingWindowSize=10
resilience4j.circuitbreaker.instances.hospitalPeriferico.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.hospitalPeriferico.failureRateThreshold=50
resilience4j.circuitbreaker.instances.hospitalPeriferico.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.hospitalPeriferico.permittedNumberOfCallsInHalfOpenState=3

# Endpoint base for peripheral hospital integration
hospital.periferico.url=${HOSPITAL_PERIFERICO_URL:http://localhost:8099}


app.jwt.secret=mi_clave_secreta_super_segura_12345678901234567890